title: "Javidan Hasanli â€“ Personal Website"
description: "SITE1101 portfolio website built with Jekyll"

remote_theme: "mmistakes/minimal-mistakes@4.24.0"

plugins:
  - jekyll-feed
  - jekyll-sitemap
  - jekyll-include-cache

url: "https://javidan19.github.io"
baseurl: "/site1101"

include:
  - _pages

author:
  name: "Javidan Hasanli"
  avatar: "/assets/images/profile.jpg"
  bio: "IT & Engineering student at ADA University."
  links:
    - label: "GitHub"
      icon: "fab fa-github"
      url: "https://github.com/Javidan19"

defaults:
  - scope:
      path: ""
      type: pages
    values:
      layout: single
      author_profile: true

sass:
  style: compressed

minimal_mistakes_skin: "dark"
