title: Javidan Hasanli
description: Personal Portfolio Website for SITE1101

url: "https://javidan19.github.io"
baseurl: "/site1101"

remote_theme: mmistakes/minimal-mistakes

plugins:
  - jekyll-feed
  - jekyll-seo-tag
  - jekyll-remote-theme

author:
  name: Javidan Hasanli

navigation:
  - title: "Home"
    url: /
  - title: "About"
    url: /about/
  - title: "Projects"
    url: /projects/
